### ISSUE TITLE
Change the `--group` option to add the system to an Inventory Group rather than add a tag

### ISSUE THREAD

**Issue by m8ram** [RedHatInsights/insights-client#156]
The current implementation of the `--group` option does not add the system to a group. Instead it creates a tag called `group` from source `insights-client` with the value specified.

I propose to change this option so that it actually adds the system to an Inventory group instead.

Also note that the README.md description is incorrect. It currently states:
```
--group=GROUP - Group to add the system to in the insights web UI. Only used on machine registration.
```
However the option can be specified on a regular run and with the `--checkin` option and will add the tag.

**Comment by ahitacat** [comment]
I think this could be a potential feature. But also this needs to be discussed with the team.

**Comment by m8ram** [comment]
Once this is implemented it can be added to the `rhc` ansible role. The feature request for that is https://github.com/linux-system-roles/rhc/issues/186

**Comment by mtward** [comment]
As part of a fairly large customer with separate groups on the same RH account, I agree that this feature would be hugely useful.  The current workaround depends on basic auth which is deprecated:  https://access.redhat.com/solutions/7063192

**Comment by m-horky** [comment]
Hey. While we recognize this use-case is valid and would be already included in the perfect world, we have no immediate plans to improve the behavior of `--group`. Especially since [Inventory Groups have been renamed to Workspaces](https://access.redhat.com/articles/7063237), our longer-term plans are to support them under a new flag with new behavior.

I'll close this issue now; if the support for workspaces is important to you and you think should be supported client-side, feel free to reach out, we could discuss that with the stakeholders and work on prioritization.
